module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: { extend: {
                    "colors": {
                        "primary-container": "#2563eb",
                        "surface-dim": "#e7ebf2",
                        "on-tertiary": "#ffffff",
                        "on-tertiary-container": "#eff1f3",
                        "outline-variant": "#ecf0f6",
                        "primary-fixed": "#dbe1ff",
                        "on-secondary": "#ffffff",
                        "on-secondary-fixed": "#131b2e",
                        "on-secondary-container": "#5c647a",
                        "tertiary-container": "#6b6e70",
                        "surface-container-highest": "#e2e7f0",
                        "surface-container-low": "#f4f6fa",
                        "tertiary-fixed": "#e0e3e5",
                        "on-primary-fixed": "#00174b",
                        "inverse-primary": "#b4c5ff",
                        "primary": "#1a3fd4",
                        "error": "#b3261e",
                        "on-surface": "#0a111e",
                        "on-primary-fixed-variant": "#12309f",
                        "on-tertiary-fixed-variant": "#444749",
                        "surface-bright": "#ffffff",
                        "surface-variant": "#eaeef6",
                        "outline": "#727a8a",
                        "on-background": "#0a111e",
                        "secondary-fixed-dim": "#bec6e0",
                        "on-secondary-fixed-variant": "#3f465c",
                        "on-error-container": "#93000a",
                        "on-primary": "#ffffff",
                        "secondary": "#3f4757",
                        "secondary-fixed": "#dae2fd",
                        "on-error": "#ffffff",
                        "surface-container": "#eaeef6",
                        "inverse-on-surface": "#e8ecf4",
                        "surface-container-lowest": "#ffffff",
                        "error-container": "#ffdad6",
                        "background": "#ffffff",
                        "surface-tint": "#0053db",
                        "secondary-container": "#dae2fd",
                        "surface-container-high": "#e5eaf3",
                        "on-tertiary-fixed": "#191c1e",
                        "inverse-surface": "#061127",
                        "surface": "#f4f6fa",
                        "tertiary": "#525657",
                        "primary-fixed-dim": "#b4c5ff",
                        "on-primary-container": "#eeefff",
                        "on-surface-variant": "#3f4757",
                        "tertiary-fixed-dim": "#c4c7c9",
                        "shell": "#061127",
                        "shell-deep": "#020916",
                        "shell-line": "#1b2942",
                        "shell-text": "#9fb0c9",
                        "accent": "#8ab4ff"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.125rem",
                        "lg": "0.1875rem",
                        "xl": "0.25rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "gutter": "20px",
                        "section-padding": "72px",
                        "stack-sm": "8px",
                        "container-max-width": "1320px",
                        "stack-lg": "32px",
                        "stack-md": "16px",
                        "margin": "22px"
                    },
                    "fontFamily": {
                        "headline-xl": ["Geist"],
                        "headline-lg-mobile": ["Geist"],
                        "headline-lg": ["Geist"],
                        "label-sm": ["Geist"],
                        "label-md": ["Geist"],
                        "headline-md": ["Geist"],
                        "body-md": ["Geist"],
                        "body-lg": ["Geist"]
                    },
                    "fontSize": {
                        "headline-xl": ["56px", { "lineHeight": "1.02", "letterSpacing": "-0.035em", "fontWeight": "600" }],
                        "headline-lg-mobile": ["26px", { "lineHeight": "1.15", "fontWeight": "600" }],
                        "headline-lg": ["38px", { "lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "600" }],
                        "label-sm": ["12px", { "lineHeight": "1.4", "fontWeight": "500" }],
                        "label-md": ["14px", { "lineHeight": "1.45", "fontWeight": "450" }],
                        "headline-md": ["24px", { "lineHeight": "1.2", "letterSpacing": "-0.022em", "fontWeight": "600" }],
                        "body-md": ["15.5px", { "lineHeight": "1.55", "fontWeight": "400" }],
                        "body-lg": ["18px", { "lineHeight": "1.55", "fontWeight": "400" }]
                    }
                } },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
